### ISSUE TITLE
DB Deadlock when stress testing with silk

### ISSUE THREAD

**Issue by selimt** [jazzband/django-silk#265]
I got a deadlock error when testing with the latest version of silk (1.1.0).

Here is the DB output:

```
        Process 149: DELETE FROM "silk_response" WHERE "silk_response"."request_id" IN ('629f685a-26dc-41ca-ba9d-cc8af1998ef9', '8336effc-217c-47a7-8cc2-6944b8aede7f', 'aa12852b-5f5b-40fa-a647-cc3ddd2ef4ba', '2b2d5e84-e595-4ccf-b06c-78db181b4f24', '3f94c00d-f0c3-4021-8def-703e363e4f8f', 'e88b9162-0455-4e78-ba7b-029694b493d8')
        Process 150: DELETE FROM "silk_response" WHERE "silk_response"."request_id" IN ('629f685a-26dc-41ca-ba9d-cc8af1998ef9', '9ad245bb-4b6a-49cf-b32c-1a547ee8c11f', '93c50572-f6ec-416c-a9d6-42798f1631dd', '1ffd6a86-f93e-48f8-a593-86184e26c417', '3f94c00d-f0c3-4021-8def-703e363e4f8f')
        Process 151: DELETE FROM "silk_response" WHERE "silk_response"."request_id" IN ('629f685a-26dc-41ca-ba9d-cc8af1998ef9', '9ad245bb-4b6a-49cf-b32c-1a547ee8c11f', 'aa12852b-5f5b-40fa-a647-cc3ddd2ef4ba', '8336effc-217c-47a7-8cc2-6944b8aede7f', '2b2d5e84-e595-4ccf-b06c-78db181b4f24', '93c50572-f6ec-416c-a9d6-42798f1631dd', '1ffd6a86-f93e-48f8-a593-86184e26c417', '3f94c00d-f0c3-4021-8def-703e363e4f8f', 'e88b9162-0455-4e78-ba7b-029694b493d8')
        Process 144: DELETE FROM "silk_response" WHERE "silk_response"."request_id" IN ('629f685a-26dc-41ca-ba9d-cc8af1998ef9', '9ad245bb-4b6a-49cf-b32c-1a547ee8c11f', 'aa12852b-5f5b-40fa-a647-cc3ddd2ef4ba', '8336effc-217c-47a7-8cc2-6944b8aede7f', '2b2d5e84-e595-4ccf-b06c-78db181b4f24', '93c50572-f6ec-416c-a9d6-42798f1631dd', '1ffd6a86-f93e-48f8-a593-86184e26c417', '3f94c00d-f0c3-4021-8def-703e363e4f8f', 'e88b9162-0455-4e78-ba7b-029694b493d8')
2018-01-26 01:03:55.996 UTC [148] HINT:  See server log for query details.
2018-01-26 01:03:55.996 UTC [148] STATEMENT:  DELETE FROM "silk_response" WHERE "silk_response"."request_id" IN ('629f685a-26dc-41ca-ba9d-cc8af1998ef9', '9ad245bb-4b6a-49cf-b32c-1a547ee8c11f', 'aa12852b-5f5b-40fa-a647-cc3ddd2ef4ba', '8336effc-217c-47a7-8cc2-6944b8aede7f', '2b2d5e84-e595-4ccf-b06c-78db181b4f24', '1ffd6a86-f93e-48f8-a593-86184e26c417', '3f94c00d-f0c3-4021-8def-703e363e4f8f', 'e88b9162-0455-4e78-ba7b-029694b493d8')
2018-01-26 01:03:56.024 UTC [144] ERROR:  deadlock detected
2018-01-26 01:03:56.024 UTC [144] DETAIL:  Process 144 waits for AccessExclusiveLock on tuple (443,8) of relation 16579 of database 12994; blocked by process 149.
        Process 149 waits for ShareLock on transaction 152027; blocked by process 150.
        Process 150 waits for AccessExclusiveLock on tuple (440,10) of relation 16579 of database 12994; blocked by process 151.
        Process 151 waits for ShareLock on transaction 152109; blocked by process 144.
```

Output from pip freeze:

```
amqp==2.2.2
autopep8==1.3.4
billiard==3.5.0.3
blessings==1.6.1
bpython==0.17
cached-property==1.3.1
celery==4.1.0
certifi==2018.1.18
chardet==3.0.4
coreapi==2.3.3
coreschema==0.0.4
coverage==4.4.2
curtsies==0.2.11
Django==1.11.9
django-auth-ldap==1.3.0
django-cachalot==1.5.0
django-extensions==1.9.9
django-model-utils==3.1.1
django-prettyjson==0.3.0
django-rest-swagger==2.1.2
django-silk==1.1.0
django-url-filter==0.3.4
djangorestframework==3.7.7
drf-extensions==0.3.1
drf-nested-routers==0.90.0
enum-compat==0.0.2
gevent==1.2.2
gprof2dot==2016.10.13
greenlet==0.4.12
gunicorn==19.7.1
idna==2.6
itypes==1.1.0
Jinja2==2.10
kombu==4.1.0
Markdown==2.6.11
MarkupSafe==1.0
mercury==1.0.0
mock==2.0.0
openapi-codec==1.3.2
pbr==3.1.1
psycopg2==2.7.3.2
pycodestyle==2.3.1
Pygments==2.2.0
pyldap==2.4.45
python-dateutil==2.6.1
python-memcached==1.59
pytz==2017.3
requests==2.18.4
simplejson==3.13.2
six==1.11.0
sqlparse==0.2.4
standardjson==0.3.1
stevedore==1.28.0
typing==3.6.4
uritemplate==3.0.0
urllib3==1.22
vine==1.1.4
wcwidth==0.1.7
Werkzeug==0.14.1
```

Thanks
-Selim

**Comment by albertyw** [comment]
Looks like the deadlock is from deleting the same rows from the garbage collector as reported in #261.  Should be fixed in #267

**Comment by hgminh95** [comment]
I still encounter this issue in v2.0.0. So maybe #267 did not fully fix this issue.

Sample logs from db:

```
ERROR:  deadlock detected
DETAIL:  Process 33723 waits for ShareLock on transaction 404208689; blocked by process 33721.
        Process 33721 waits for ShareLock on transaction 404208701; blocked by process 33723.
        Process 33723: DELETE FROM "silk_response" WHERE "silk_response"."request_id" IN ('d6563662-8303-4b97-ad93-afacf36489aa', '3e526532-8785-47e8-ba3a-afd7f709ffd6', '854ea9ac-5f81-4346-b0a9-26b39c35a81c')
        Process 33721: DELETE FROM "silk_response" WHERE "silk_response"."request_id" IN ('3e526532-8785-47e8-ba3a-afd7f709ffd6', '854ea9ac-5f81-4346-b0a9-26b39c35a81c')
```

**Comment by gone** [comment]
I still get this as well -  I think it might be related to cachealot which I have installed as well.  Trying to turn off cachealot for silk via 
`CACHALOT_UNCACHABLE_TABLES = frozenset(('django_migrations', 'silk_response'))` 
And seeing if that works

**Comment by bj00rn** [comment]
getting this as well. Serving django through 4x daphne workers

```
 File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
     return self.cursor.execute(sql, params)
 psycopg2.extensions.TransactionRollbackError: deadlock detected
 DETAIL:  Process 4930 waits for AccessExclusiveLock on tuple (9,89) of relation 21806 of database 20072; blocked by process 4929.
 Process 4929 waits for ShareLock on transaction 94641; blocked by process 4928.
 Process 4928 waits for ShareLock on transaction 94582; blocked by process 4926.
 Process 4926 waits for AccessExclusiveLock on tuple (9,89) of relation 21806 of database 20072; blocked by process 4930.
 HINT:  See server log for query details.


 The above exception was the direct cause of the following exception:

 Traceback (most recent call last):
   File "/usr/local/lib/python3.6/site-packages/silk/middleware.py", line 128, in process_response
     self._process_response(request, response)
   File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
     return func(*args, **kwds)
   File "/usr/local/lib/python3.6/site-packages/silk/middleware.py", line 110, in _process_response
     collector.finalise()
   File "/usr/local/lib/python3.6/site-packages/silk/collector.py", line 158, in finalise
     query_model = models.SQLQuery.objects.create(**query)
   File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
     return getattr(self.get_queryset(), name)(*args, **kwargs)
   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 394, in create
     obj.save(force_insert=True, using=self.db)
   File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
     return func(*args, **kwds)
   File "/usr/local/lib/python3.6/site-packages/silk/models.py", line 283, in save
     self.request.save(update_fields=['num_sql_queries'])
   File "/usr/local/lib/python3.6/site-packages/silk/models.py", line 167, in save
     Request.garbage_collect(force=False)
   File "/usr/local/lib/python3.6/site-packages/silk/models.py", line 152, in garbage_collect
     cls.objects.filter(start_time__lte=time_cutoff).delete()
   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 620, in delete
     deleted, _rows_count = collector.delete()
   File "/usr/local/lib/python3.6/site-packages/django/db/models/deletion.py", line 284, in delete
     count = qs._raw_delete(using=self.using)
   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 634, in _raw_delete
     return sql.DeleteQuery(self.model).delete_qs(self, using)
   File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/subqueries.py", line 80, in delete_qs
     cursor = self.get_compiler(using).execute_sql(CURSOR)
   File "/usr/local/lib/python3.6/site-packages/silk/sql.py", line 45, in execute_sql
     return self._execute_sql(*args, **kwargs)
   File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
     raise original_exception
   File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 889, in execute_sql
     cursor.execute(sql, params)
   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
     return self.cursor.execute(sql, params)
   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
     six.reraise(dj_exc_type, dj_exc_value, traceback)
   File "/usr/local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
     raise value.with_traceback(tb)
   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
     return self.cursor.execute(sql, params)
 django.db.utils.OperationalError: deadlock detected
 DETAIL:  Process 4930 waits for AccessExclusiveLock on tuple (9,89) of relation 21806 of database 20072; blocked by process 4929.
 Process 4929 waits for ShareLock on transaction 94641; blocked by process 4928.
 Process 4928 waits for ShareLock on transaction 94582; blocked by process 4926.
 Process 4926 waits for AccessExclusiveLock on tuple (9,89) of relation 21806 of database 20072; blocked by process 4930.
 HINT:  See server log for query details.


 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/usr/local/lib/python3.6/site-packages/silk/middleware.py", line 110, in _process_response
     collector.finalise()
   File "/usr/local/lib/python3.6/site-packages/silk/collector.py", line 158, in finalise
     query_model = models.SQLQuery.objects.create(**query)
   File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
     return getattr(self.get_queryset(), name)(*args, **kwargs)
   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 392, in create
     obj = self.model(**kwargs)
   File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 573, in __init__
     raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
 TypeError: 'model' is an invalid keyword argument for this function
```
...
 ERROR:  deadlock detected
 DETAIL:  Process 4920 waits for ShareLock on transaction 94582; blocked by process 4926.
      Process 4926 waits for AccessExclusiveLock on tuple (9,89) of relation 21806 of database 20072; blocked by process 4929.
      Process 4929 waits for ShareLock on transaction 94641; blocked by process 4928.
      Process 4928 waits for AccessExclusiveLock on tuple (44,75) of relation 21806 of database 20072; blocked by process 4920.
      Process 4920: DELETE FROM "silk_response" WHERE "silk_response"."request_id" IN ('98a609f6-178c-4754-91d9-a500287f1a6e', '87277d11-24c6-481c-a51d-40adcad0891b', '0fce5919-c945-43ca-939f-915c6b89cb3a', '20eb66ac-23ee-466e-add7-888c98071a0f', 'f810b99c-446e-4272-88e0-4722ba133474', '92251ef1-feb4-4c72-a061-f04ebf8fb0a2', '6379e858-f6fc-44d3-aa5d-edc338c1683e', '436ff660-e456-42b3-ab88-018f18159d09')
      Process 4926: DELETE FROM "silk_response" WHERE "silk_response"."request_id" IN ('80a46b34-8b35-455b-9b12-ab8ae03121d3', 'a46762ea-9262-4943-b95c-171fb98f2fcd', '2d9bbe1d-43e2-4a17-afe6-8ddcd8b2036c', '45a61cf6-45c2-4a38-824c-0d9774db54d2', 'ed59a924-4830-4b92-8e56-cea6cd2ea273')
      Process 4929: DELETE FROM "silk_response" WHERE "silk_response"."request_id" IN ('a46762ea-9262-4943-b95c-171fb98f2fcd', '80a46b34-8b35-455b-9b12-ab8ae03121d3', '2d9bbe1d-43e2-4a17-afe6-8ddcd8b2036c', 'f810b99c-446e-4272-88e0-4722ba133474', '87277d11-24c6-481c-a51d-40adcad0891b', '45a61cf6-45c2-4a38-824c-0d9774db54d2')
      Process 4928: DELETE FROM "silk_response" WHERE "silk_response"."request_id" IN ('80a46b34-8b35-455b-9b12-ab8ae03121d3', '45a61cf6-45c2-4a38-824c-0d9774db54d2', '87277d11-24c6-481c-a51d-40adcad0891b', '0fce5919-c945-43ca-939f-915c6b89cb3a', 'a46762ea-9262-4943-b95c-171fb98f2fcd', '20eb66ac-23ee-466e-add7-888c98071a0f', 'f810b99c-446e-4272-88e0-4722ba133474', '6379e858-f6fc-44d3-aa5d-edc338c1683e')
 HINT:  See server log for query details.
 CONTEXT:  while deleting tuple (44,75) in relation "silk_response"
 STATEMENT:  DELETE FROM "silk_response" WHERE "silk_response"."request_id" IN ('98a609f6-178c-4754-91d9-a500287f1a6e', '87277d11-24c6-481c-a51d-40adcad0891b', '0fce5919-c945-43ca-939f-915c6b89cb3a', '20eb66ac-23ee-466e-add7-888c98071a0f', 'f810b99c-446e-4272-88e0-4722ba133474', '92251ef1-feb4-4c72-a061-f04ebf8fb0a2', '6379e858-f6fc-44d3-aa5d-edc338c1683e', '436ff660-e456-42b3-ab88-018f18159d09')
 ERROR:  deadlock detected
 DETAIL:  Process 4930 waits for AccessExclusiveLock on tuple (9,89) of relation 21806 of database 20072; blocked by process 4929.
      Process 4929 waits for ShareLock on transaction 94641; blocked by process 4928.
      Process 4928 waits for ShareLock on transaction 94582; blocked by process 4926.
      Process 4926 waits for AccessExclusiveLock on tuple (9,89) of relation 21806 of database 20072; blocked by process 4930.
      Process 4930: DELETE FROM "silk_response" WHERE "silk_response"."request_id" IN ('80a46b34-8b35-455b-9b12-ab8ae03121d3', '87277d11-24c6-481c-a51d-40adcad0891b', 'a46762ea-9262-4943-b95c-171fb98f2fcd', '2d9bbe1d-43e2-4a17-afe6-8ddcd8b2036c', '45a61cf6-45c2-4a38-824c-0d9774db54d2', 'f810b99c-446e-4272-88e0-4722ba133474')
      Process 4929: DELETE FROM "silk_response" WHERE "silk_response"."request_id" IN ('a46762ea-9262-4943-b95c-171fb98f2fcd', '80a46b34-8b35-455b-9b12-ab8ae03121d3', '2d9bbe1d-43e2-4a17-afe6-8ddcd8b2036c', 'f810b99c-446e-4272-88e0-4722ba133474', '87277d11-24c6-481c-a51d-40adcad0891b', '45a61cf6-45c2-4a38-824c-0d9774db54d2')
      Process 4928: DELETE FROM "silk_response" WHERE "silk_response"."request_id" IN ('80a46b34-8b35-455b-9b12-ab8ae03121d3', '45a61cf6-45c2-4a38-824c-0d9774db54d2', '87277d11-24c6-481c-a51d-40adcad0891b', '0fce5919-c945-43ca-939f-915c6b89cb3a', 'a46762ea-9262-4943-b95c-171fb98f2fcd', '20eb66ac-23ee-466e-add7-888c98071a0f', 'f810b99c-446e-4272-88e0-4722ba133474', '6379e858-f6fc-44d3-aa5d-edc338c1683e')
      Process 4926: DELETE FROM "silk_response" WHERE "silk_response"."request_id" IN ('80a46b34-8b35-455b-9b12-ab8ae03121d3', 'a46762ea-9262-4943-b95c-171fb98f2fcd', '2d9bbe1d-43e2-4a17-afe6-8ddcd8b2036c', '45a61cf6-45c2-4a38-824c-0d9774db54d2', 'ed59a924-4830-4b92-8e56-cea6cd2ea273')
 HINT:  See server log for query details.
 STATEMENT:  DELETE FROM "silk_response" WHERE "silk_response"."request_id" IN ('80a46b34-8b35-455b-9b12-ab8ae03121d3', '87277d11-24c6-481c-a51d-40adcad0891b', 'a46762ea-9262-4943-b95c-171fb98f2fcd', '2d9bbe1d-43e2-4a17-afe6-8ddcd8b2036c', '45a61cf6-45c2-4a38-824c-0d9774db54d2', 'f810b99c-446e-4272-88e0-4722ba133474')
 ERROR:  deadlock detected
 DETAIL:  Process 4926 waits for AccessExclusiveLock on tuple (9,89) of relation 21806 of database 20072; blocked by process 4929.
      Process 4929 waits for ShareLock on transaction 94641; blocked by process 4928.
      Process 4928 waits for ShareLock on transaction 94582; blocked by process 4926.
      Process 4926: DELETE FROM "silk_response" WHERE "silk_response"."request_id" IN ('80a46b34-8b35-455b-9b12-ab8ae03121d3', 'a46762ea-9262-4943-b95c-171fb98f2fcd', '2d9bbe1d-43e2-4a17-afe6-8ddcd8b2036c', '45a61cf6-45c2-4a38-824c-0d9774db54d2', 'ed59a924-4830-4b92-8e56-cea6cd2ea273')
      Process 4929: DELETE FROM "silk_response" WHERE "silk_response"."request_id" IN ('a46762ea-9262-4943-b95c-171fb98f2fcd', '80a46b34-8b35-455b-9b12-ab8ae03121d3', '2d9bbe1d-43e2-4a17-afe6-8ddcd8b2036c', 'f810b99c-446e-4272-88e0-4722ba133474', '87277d11-24c6-481c-a51d-40adcad0891b', '45a61cf6-45c2-4a38-824c-0d9774db54d2')
      Process 4928: DELETE FROM "silk_response" WHERE "silk_response"."request_id" IN ('80a46b34-8b35-455b-9b12-ab8ae03121d3', '45a61cf6-45c2-4a38-824c-0d9774db54d2', '87277d11-24c6-481c-a51d-40adcad0891b', '0fce5919-c945-43ca-939f-915c6b89cb3a', 'a46762ea-9262-4943-b95c-171fb98f2fcd', '20eb66ac-23ee-466e-add7-888c98071a0f', 'f810b99c-446e-4272-88e0-4722ba133474', '6379e858-f6fc-44d3-aa5d-edc338c1683e')
 HINT:  See server log for query details.
 STATEMENT:  DELETE FROM "silk_response" WHERE "silk_response"."request_id" IN ('80a46b34-8b35-455b-9b12-ab8ae03121d3', 'a46762ea-9262-4943-b95c-171fb98f2fcd', '2d9bbe1d-43e2-4a17-afe6-8ddcd8b2036c', '45a61cf6-45c2-4a38-824c-0d9774db54d2', 'ed59a924-4830-4b92-8e56-cea6cd2ea273')
...
```

**Comment by vakorol** [comment]
Can't use `django-silk` in our development environment because of this issue. Requests fail quite frequently with :

```
Exception Type: OperationalError at /static/img/favicon.ico
Exception Value: (1213, 'Deadlock found when trying to get lock; try restarting transaction')

"DELETE FROM `silk_response` WHERE `silk_response`.`request_id` IN ( ..., ..., ...)"
```
MySQL 5.5
Django 1.11.20
Python 3.4.3
django-silk 3.0.2

**Comment by worsht** [comment]
I'm seeing this as well.

python 3.7.3
postgres 11
django 2.2.4
django-silk 3.0.2

**Comment by gone** [comment]
Since configuring cachealot and silk to work together this error went away for me. 


```
CACHALOT_UNCACHABLE_TABLES = frozenset(
    ("django_migrations", "silk_response", "silk_sqlquery", "silk_profile")
)
```

**Comment by aurashn** [comment]
Has anyone solved this issue? I am seeing this with:

Python 3.6
MySQL 5.6
django 2.2.5
django-silk 3.0.4

**Comment by vakorol** [comment]
**I would like to draw the maintainers' attention to this issue**, as it seems to affect multiple users. In fact, it is a blocker for me; I would really like to use `django-silk` in my projects, but I am unable to do so due to this problem.

**Comment by AdamMartinCote** [comment]
I am experiencing the same issue with Postgres
Python 3.8
Postgres 12.2
django 3.0.6
django-silk 4.0.1

**Comment by okke-formsma** [comment]
As a workaround, make sure to set the `SILKY_MAX_RECORDED_REQUESTS_CHECK_PERCENT` very low (0.01 for example) and the `SILKY_MAX_RECORDED_REQUESTS` high (100_000 or more).

This way, the chances of running into this issue are much smaller.

An even better workaround is to set `SILKY_MAX_RECORDED_REQUESTS_CHECK_PERCENT` to 0 and run the `silky.Request.garbage_collect` method in a scheduled task through celery.

**Comment by waqas-ali-pk** [comment]
Issue still exists. :( 

Any plan to resolve this annoying issue?
